package util

const colorNone        = "0"
const ColorBlack       = "0;30"
const ColorBlue        = "0;34"
const ColorGreen       = "0;32"
const ColorCyan        = "0;36"
const ColorRed         = "0;31"
const ColorPurple      = "0;35"
const ColorBrown       = "0;33"
const ColorLightGray   = "0;37"
const ColorDarkGray    = "1;30"
const ColorLightBlue   = "1;34"
const ColorLightGreen  = "1;32"
const ColorLightCyan   = "1;36"
const ColorLightRed    = "1;31"
const ColorLightPurple = "1;35"
const ColorYellow      = "1;33"
const ColorWhite       = "1;37"
